### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by wiiznokes** [cosmic-utils/clipboard-manager#102]
```
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: thread 'main' panicked at src/app.rs:52:24:
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: attempt to calculate the remainder with a divisor of zero
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: stack backtrace:
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    0: rust_begin_unwind
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    1: core::panicking::panic_fmt
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    2: core::panicking::panic_const::panic_const_rem_by_zero
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    3: cosmic_ext_applet_clipboard_manager::app::AppState::focus_next
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    4: <cosmic_ext_applet_clipboard_manager::app::AppState as cosmic::app::Application>::update
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    5: <T as iced::application::Update<State,Message>>::update
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    6: <cosmic::executor::single::Executor as iced_futures::executor::Executor>::enter
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    7: iced_winit::program::run_instance::{{closure}}
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    8: iced_winit::program::run::Runner<Message,F,C>::process_event
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    9: winit::platform_impl::linux::wayland::event_loop::EventLoop::single_iteration
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   10: winit::platform_impl::linux::wayland::event_loop::EventLoop::run_app
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   11: iced_winit::program::run
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   12: cosmic::applet::run
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   13: cosmic_ext_applet_clipboard_manager::main
nov. 20 16:22:27 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.****
```

**Comment by wiiznokes** [comment]
Maybe unrelated, but there was another panic when copying smtg after this panic

```
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: thread 'tokio-runtime-worker' panicked at src/clipboard.rs:103:65:
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: can't send: SendError { .. }
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: stack backtrace:
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    0: rust_begin_unwind
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    1: core::panicking::panic_fmt
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    2: core::result::unwrap_failed
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    3: cosmic_ext_applet_clipboard_manager::clipboard::sub::{{closure}}::{{closure}}::{{closure}}
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    4: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    5: tokio::runtime::task::raw::poll
nov. 20 16:22:52 fedasus cosmic-panel[17726]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    6: tokio::runtime::blocking::pool::Inner::run
```

**Comment by wiiznokes** [comment]
to reproduce: focus_next when there is no entry
